---
title: "Getting a Data Science Job Using Data Science"
subtitle: "A Presentation by Melanie Desroches"
format:
    revealjs:
        self-contained: true
        slide-number: true
        preview-links: true
        theme: solarized
---

# Background

## Data Science Jobs

- As the collection of data becomes more important across a variety of industries,
the need for trained data scientists as increased. 
- According to the US Bureau of Labor Statistics, there has been a 36% growth in 
data science jobs (compared to the average job growth of 4%).
- What does it take to get a data science related job?
- What are the skills that are valued in these positions?

# Research Question

## What skills are important for different data science jobs?

- What are the most important skills for a job as a data scientist?
- What are the most important skills for a job as a data analyst?
- What are the most important skills for a job as a machine learning engineer?
- What are the most important skills for a job as a data engineer?

# Data

## Data

- The dataset consists of job postings related to data science
- The data set was collected from Kaggle
- There are 660 postings in total
- Some relevant columns are the job description and the job title

## Feature Engineering

- To answer the research question, feature engineering:  
  - Identified prevalent skills in the job descriptions.  
  - Created **boolean columns** indicating whether a skill was mentioned.  
- The identified skills include:  
  - **Programming Skills**: Python, SQL, Java, C++, Scala, R  
  - **Big Data Tools**: Hadoop, Spark, AWS, Git, Linux, Azure  
  - **Visualization Tools**: Tableau, Matlab  
  - **Soft Skills**: Communication, leadership, collaboration, problem-solving, critical thinking  

# Methods

## Random Forests

- A **Random Forest classifier** was used to analyze the skills data.  
- The goal was to identify the most important skills for each job type.  
- The model evaluated the presence of skills against job titles (e.g., data scientist, analyst, machine learning engineer, data engineer, etc.).


## Results




## Evaluating the Model




# Discussion

## What did we learn?




## Possible Limitations




# Thank you

